# Generated by Django 6.0 on 2025-12-11 03:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('maiden_name', models.CharField(blank=True, help_text='Birth surname if different', max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_date_fuzzy', models.CharField(blank=True, help_text="e.g. 'About 1900' or 'Winter 1890'", max_length=50)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('is_living', models.BooleanField(default=True)),
                ('confidence_level', models.IntegerField(default=100, help_text='0=Rumor, 100=Verified Fact')),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='ParentChildLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('BIO', 'Biological'), ('ADO', 'Adopted'), ('FOS', 'Foster'), ('STP', 'Step-Child')], default='BIO', max_length=3)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='api.person')),
                ('single_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_children', to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('MAR', 'Married'), ('PAR', 'Unmarried Partners'), ('DIV', 'Divorced'), ('UNK', 'Unknown')], default='MAR', max_length=3)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('children', models.ManyToManyField(related_name='parents_relationship', through='api.ParentChildLink', through_fields=('relationship', 'child'), to='api.person')),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_a', to='api.person')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_b', to='api.person')),
            ],
        ),
        migrations.AddField(
            model_name='parentchildlink',
            name='relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.relationship'),
        ),
    ]
