# Generated by Django 6.0 on 2025-12-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_story_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="death_date_fuzzy",
            field=models.CharField(
                blank=True, help_text="e.g. 'About 1950'", max_length=50
            ),
        ),
    ]
